# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressBook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressBook.proto',
  package='addressBook',
  serialized_pb=_b('\n\x11\x61\x64\x64ressBook.proto\x12\x0b\x61\x64\x64ressBook\"\xe0\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12.\n\x05phone\x18\x04 \x03(\x0b\x32\x1f.addressBook.Person.PhoneNumber\x1aP\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x02(\t\x12\x31\n\x04type\x18\x02 \x01(\x0e\x32\x1d.addressBook.Person.PhoneType:\x04HOME\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"2\n\x0b\x41\x64\x64ressBook\x12#\n\x06person\x18\x01 \x03(\x0b\x32\x13.addressBook.Person\" \n\x10GetPersonRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\"A\n\x11GetPersonResponse\x12,\n\x0frequestedPerson\x18\x01 \x02(\x0b\x32\x13.addressBook.Person\" \n\x11\x41\x64\x64PersonResponse\x12\x0b\n\x03msg\x18\x01 \x02(\t\"5\n\x0eGetAllResponse\x12#\n\x06person\x18\x01 \x03(\x0b\x32\x13.addressBook.Person\"\x1e\n\rGetAllRequest\x12\r\n\x05\x64ummy\x18\x01 \x01(\t2\xe5\x01\n\x12\x41\x64\x64ressBookService\x12@\n\tAddPerson\x12\x13.addressBook.Person\x1a\x1e.addressBook.AddPersonResponse\x12J\n\tGetPerson\x12\x1d.addressBook.GetPersonRequest\x1a\x1e.addressBook.GetPersonResponse\x12\x41\n\x06GetAll\x12\x1a.addressBook.GetAllRequest\x1a\x1b.addressBook.GetAllResponse')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PERSON_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='addressBook.Person.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=216,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_PERSON_PHONETYPE)


_PERSON_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='addressBook.Person.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='addressBook.Person.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='addressBook.Person.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=214,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='addressBook.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='addressBook.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='addressBook.Person.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='addressBook.Person.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='addressBook.Person.phone', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_PHONENUMBER, ],
  enum_types=[
    _PERSON_PHONETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=259,
)


_ADDRESSBOOK = _descriptor.Descriptor(
  name='AddressBook',
  full_name='addressBook.AddressBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='addressBook.AddressBook.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=311,
)


_GETPERSONREQUEST = _descriptor.Descriptor(
  name='GetPersonRequest',
  full_name='addressBook.GetPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='addressBook.GetPersonRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=345,
)


_GETPERSONRESPONSE = _descriptor.Descriptor(
  name='GetPersonResponse',
  full_name='addressBook.GetPersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestedPerson', full_name='addressBook.GetPersonResponse.requestedPerson', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=412,
)


_ADDPERSONRESPONSE = _descriptor.Descriptor(
  name='AddPersonResponse',
  full_name='addressBook.AddPersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='addressBook.AddPersonResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=446,
)


_GETALLRESPONSE = _descriptor.Descriptor(
  name='GetAllResponse',
  full_name='addressBook.GetAllResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='addressBook.GetAllResponse.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=501,
)


_GETALLREQUEST = _descriptor.Descriptor(
  name='GetAllRequest',
  full_name='addressBook.GetAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy', full_name='addressBook.GetAllRequest.dummy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=533,
)

_PERSON_PHONENUMBER.fields_by_name['type'].enum_type = _PERSON_PHONETYPE
_PERSON_PHONENUMBER.containing_type = _PERSON
_PERSON.fields_by_name['phone'].message_type = _PERSON_PHONENUMBER
_PERSON_PHONETYPE.containing_type = _PERSON
_ADDRESSBOOK.fields_by_name['person'].message_type = _PERSON
_GETPERSONRESPONSE.fields_by_name['requestedPerson'].message_type = _PERSON
_GETALLRESPONSE.fields_by_name['person'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['AddressBook'] = _ADDRESSBOOK
DESCRIPTOR.message_types_by_name['GetPersonRequest'] = _GETPERSONREQUEST
DESCRIPTOR.message_types_by_name['GetPersonResponse'] = _GETPERSONRESPONSE
DESCRIPTOR.message_types_by_name['AddPersonResponse'] = _ADDPERSONRESPONSE
DESCRIPTOR.message_types_by_name['GetAllResponse'] = _GETALLRESPONSE
DESCRIPTOR.message_types_by_name['GetAllRequest'] = _GETALLREQUEST

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(

  PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), dict(
    DESCRIPTOR = _PERSON_PHONENUMBER,
    __module__ = 'addressBook_pb2'
    # @@protoc_insertion_point(class_scope:addressBook.Person.PhoneNumber)
    ))
  ,
  DESCRIPTOR = _PERSON,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.Person)
  ))
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.PhoneNumber)

AddressBook = _reflection.GeneratedProtocolMessageType('AddressBook', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSBOOK,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.AddressBook)
  ))
_sym_db.RegisterMessage(AddressBook)

GetPersonRequest = _reflection.GeneratedProtocolMessageType('GetPersonRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPERSONREQUEST,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.GetPersonRequest)
  ))
_sym_db.RegisterMessage(GetPersonRequest)

GetPersonResponse = _reflection.GeneratedProtocolMessageType('GetPersonResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPERSONRESPONSE,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.GetPersonResponse)
  ))
_sym_db.RegisterMessage(GetPersonResponse)

AddPersonResponse = _reflection.GeneratedProtocolMessageType('AddPersonResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDPERSONRESPONSE,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.AddPersonResponse)
  ))
_sym_db.RegisterMessage(AddPersonResponse)

GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETALLRESPONSE,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.GetAllResponse)
  ))
_sym_db.RegisterMessage(GetAllResponse)

GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLREQUEST,
  __module__ = 'addressBook_pb2'
  # @@protoc_insertion_point(class_scope:addressBook.GetAllRequest)
  ))
_sym_db.RegisterMessage(GetAllRequest)


import abc
from grpc.early_adopter import implementations
from grpc.early_adopter import utilities
class EarlyAdopterAddressBookServiceServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def AddPerson(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetPerson(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetAll(self, request, context):
    raise NotImplementedError()
class EarlyAdopterAddressBookServiceServer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def start(self):
    raise NotImplementedError()
  @abc.abstractmethod
  def stop(self):
    raise NotImplementedError()
class EarlyAdopterAddressBookServiceStub(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def AddPerson(self, request):
    raise NotImplementedError()
  AddPerson.async = None
  @abc.abstractmethod
  def GetPerson(self, request):
    raise NotImplementedError()
  GetPerson.async = None
  @abc.abstractmethod
  def GetAll(self, request):
    raise NotImplementedError()
  GetAll.async = None
def early_adopter_create_AddressBookService_server(servicer, port, root_certificates, key_chain_pairs):
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  method_service_descriptions = {
    "AddPerson": utilities.unary_unary_service_description(
      servicer.AddPerson,
      addressBook_pb2.Person.FromString,
      addressBook_pb2.AddPersonResponse.SerializeToString,
    ),
    "GetAll": utilities.unary_unary_service_description(
      servicer.GetAll,
      addressBook_pb2.GetAllRequest.FromString,
      addressBook_pb2.GetAllResponse.SerializeToString,
    ),
    "GetPerson": utilities.unary_unary_service_description(
      servicer.GetPerson,
      addressBook_pb2.GetPersonRequest.FromString,
      addressBook_pb2.GetPersonResponse.SerializeToString,
    ),
  }
  return implementations.secure_server(method_service_descriptions, port, root_certificates, key_chain_pairs)
def early_adopter_create_AddressBookService_stub(host, port):
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  import addressBook_pb2
  method_invocation_descriptions = {
    "AddPerson": utilities.unary_unary_invocation_description(
      addressBook_pb2.Person.SerializeToString,
      addressBook_pb2.AddPersonResponse.FromString,
    ),
    "GetAll": utilities.unary_unary_invocation_description(
      addressBook_pb2.GetAllRequest.SerializeToString,
      addressBook_pb2.GetAllResponse.FromString,
    ),
    "GetPerson": utilities.unary_unary_invocation_description(
      addressBook_pb2.GetPersonRequest.SerializeToString,
      addressBook_pb2.GetPersonResponse.FromString,
    ),
  }
  return implementations.insecure_stub(method_invocation_descriptions, host, port)
# @@protoc_insertion_point(module_scope)
